/**
 * Synthetic edge-case corpus tests.
 *
 * Fixtures are generated by `tests/fixtures/generate-edge-cases.ts`
 * (npm run fixtures:edge) and committed to the repo.
 *
 * Several assertions below intentionally document CURRENT BUGGY BEHAVIOR
 * so we notice when it changes. Look for comments starting with "BUG:".
 */
import { describe, it, expect, vi } from "vitest";
import { resolve, dirname } from "path";
import { fileURLToPath } from "url";
import { parse } from "../src/parsers/router.js";
import { parsePlaintext } from "../src/parsers/plaintext.js";
import { parseDocx } from "../src/parsers/docx.js";
import { parseXlsx } from "../src/parsers/xlsx.js";
import { parsePptx } from "../src/parsers/pptx.js";
import { parsePdf } from "../src/parsers/pdf.js";

// Mock OCR so the real pdf path doesn't try to shell out
vi.mock("../src/ocr/detector.js", () => ({ isScanned: vi.fn(() => false) }));
vi.mock("../src/ocr/tesseract.js", () => ({
  hasTesseract: vi.fn(async () => false),
  runTesseract: vi.fn(async () => ""),
}));
vi.mock("../src/ocr/anthropic-vision.js", () => ({
  parseWithAnthropic: vi.fn(async () => ""),
}));

const __dirname = dirname(fileURLToPath(import.meta.url));
const E = resolve(__dirname, "fixtures/edge-cases");

// ──────────────────────────────────────────────────────────────
// PDF
// ──────────────────────────────────────────────────────────────
describe("edge cases: PDF", () => {
  it("truncated PDF returns empty text + failure warning", async () => {
    const r = await parsePdf(resolve(E, "truncated.pdf"));
    expect(r.text).toBe("");
    expect(r.warnings.join(" ")).toMatch(/Failed to parse/i);
  });

  // BUG: pdf-parse 1.1.1 fails to parse PDFs produced by the bundled pdfkit
  // (blank page or text-only) with "bad XRef entry". Both `blank.pdf` and
  // `table.pdf` are valid PDFs per pdfkit but trigger the same error.
  // Documented here — do not fix in this PR. See tech-debt.
  it("blank PDF (pdfkit-generated): pdf-parse currently errors with bad XRef", async () => {
    const r = await parsePdf(resolve(E, "blank.pdf"));
    expect(r.text).toBe("");
    expect(r.warnings.join(" ")).toMatch(/bad XRef|Failed to parse/i);
  });

  it("table PDF (pdfkit-generated): pdf-parse currently errors with bad XRef", async () => {
    const r = await parsePdf(resolve(E, "table.pdf"));
    // BUG: when pdf-parse is fixed, this should extract "SOP-001" etc.
    expect(r.warnings.join(" ")).toMatch(/bad XRef|Failed to parse/i);
  });
});

// ──────────────────────────────────────────────────────────────
// DOCX
// ──────────────────────────────────────────────────────────────
describe("edge cases: DOCX", () => {
  it("truncated DOCX returns empty text + corrupt-zip warning", async () => {
    const r = await parseDocx(resolve(E, "truncated.docx"));
    expect(r.text).toBe("");
    expect(r.warnings.join(" ")).toMatch(/Corrupted zip|Failed to parse/i);
  });

  it("DOCX with Cyrillic + Greek text preserves non-Latin characters", async () => {
    const r = await parseDocx(resolve(E, "cyrillic.docx"));
    expect(r.method).toBe("mammoth");
    expect(r.text).toContain("Привет мир");
    expect(r.text).toContain("Γειά σου κόσμε");
    expect(r.warnings).toHaveLength(0);
  });
});

// ──────────────────────────────────────────────────────────────
// XLSX
// ──────────────────────────────────────────────────────────────
describe("edge cases: XLSX", () => {
  it("multi-sheet workbook emits a header line per sheet", async () => {
    const r = await parseXlsx(resolve(E, "multi-sheet.xlsx"));
    expect(r.text).toContain("--- Sheet: Summary ---");
    expect(r.text).toContain("--- Sheet: Details ---");
    expect(r.text).toContain("Alice");
    expect(r.text).toContain("Widget");
    expect(r.metadata.sheetCount).toBe("2");
  });

  it("workbook with formulas: emits cached result values", async () => {
    const r = await parseXlsx(resolve(E, "formulas.xlsx"));
    expect(r.text).not.toContain("[object Object]");
    expect(r.text).toContain("3");
    expect(r.text).toContain("30");
    expect(r.text).toContain("33");
  });

  it("workbook with dates: emits deterministic ISO-8601 dates", async () => {
    const r = await parseXlsx(resolve(E, "dates.xlsx"));
    expect(r.text).toContain("2026-01-15");
    expect(r.text).toContain("2026-02-20");
    expect(r.text).toContain("Kickoff");
  });

  it("empty workbook still emits the sheet header", async () => {
    const r = await parseXlsx(resolve(E, "empty.xlsx"));
    expect(r.text).toContain("--- Sheet: Empty ---");
    expect(r.warnings).toHaveLength(0);
  });

  it("merged cells: master value appears exactly once across the merge range", async () => {
    const r = await parseXlsx(resolve(E, "merged.xlsx"));
    const firstRow = r.text.split("\n").find((l) => l.includes("Header spans"))!;
    expect(firstRow.split("\t").filter((c) => c === "Header spans two cols")).toHaveLength(1);
  });

  it("truncated XLSX returns empty text + ExcelJS failure warning", async () => {
    const r = await parseXlsx(resolve(E, "truncated.xlsx"));
    expect(r.text).toBe("");
    expect(r.warnings.join(" ")).toMatch(/ExcelJS failed|Corrupted zip/i);
  });
});

// ──────────────────────────────────────────────────────────────
// PPTX
// ──────────────────────────────────────────────────────────────
describe("edge cases: PPTX", () => {
  it("multi-slide deck returns text from every slide", async () => {
    const r = await parsePptx(resolve(E, "multi-slide.pptx"));
    expect(r.method).toBe("pptx");
    expect(r.pageCount).toBe(3);
    expect(r.text).toContain("Title Slide");
    expect(r.text).toContain("Intro body text");
    expect(r.text).toContain("Second Slide");
    expect(r.text).toContain("Middle body text");
    expect(r.text).toContain("Third Slide");
    expect(r.text).toContain("Final body text");
  });
});

// ──────────────────────────────────────────────────────────────
// Plaintext encodings
// ──────────────────────────────────────────────────────────────
describe("edge cases: plaintext encodings", () => {
  it("UTF-8 with BOM: strict UTF-8 decoder accepts the BOM (passes through)", async () => {
    const r = await parsePlaintext(resolve(E, "utf8-bom.txt"));
    // BOM is passed through as U+FEFF — consumers must strip it themselves.
    // Current behavior: raw text contains "hello world" (possibly with BOM prefix).
    expect(r.text).toContain("hello world");
    expect(r.warnings).toHaveLength(0);
  });

  it("UTF-16 LE BOM: detected via BOM and decoded correctly", async () => {
    const r = await parsePlaintext(resolve(E, "utf16-le.txt"));
    expect(r.text).toContain("hi");
    expect(r.warnings.join(" ")).toMatch(/utf-16le/);
  });

  it("UTF-16 BE BOM: detected via BOM and decoded correctly", async () => {
    const r = await parsePlaintext(resolve(E, "utf16-be.txt"));
    expect(r.text).toContain("hi");
    expect(r.warnings.join(" ")).toMatch(/utf-16be/);
  });

  it("Windows-1252 smart quotes + euro: detected and decoded correctly", async () => {
    const r = await parsePlaintext(resolve(E, "windows-1252.txt"));
    expect(r.text).toContain("Hello");
    expect(r.text).toContain("world");
    expect(r.text).toContain("\u201C");
    expect(r.text).toContain("\u201D");
    expect(r.text).toContain("€");
    expect(r.warnings.join(" ")).toMatch(/windows-1252/);
  });
});

// ──────────────────────────────────────────────────────────────
// Plaintext misc
// ──────────────────────────────────────────────────────────────
describe("edge cases: plaintext misc", () => {
  it("CSV with quoted commas and embedded newlines is returned verbatim", async () => {
    const r = await parsePlaintext(resolve(E, "quoted.csv"));
    expect(r.text).toContain('"Smith, John"');
    expect(r.text).toContain('"line1\nline2"');
  });

  it("CRLF line endings are preserved verbatim", async () => {
    const r = await parsePlaintext(resolve(E, "crlf.txt"));
    expect(r.text).toContain("\r\n");
    expect(r.text).toContain("line one");
    expect(r.text).toContain("line three");
  });

  it("CR-only line endings are preserved verbatim", async () => {
    const r = await parsePlaintext(resolve(E, "cr.txt"));
    expect(r.text).toContain("\r");
    expect(r.text).not.toContain("\n");
  });

  it("empty file returns empty text with no warnings", async () => {
    const r = await parsePlaintext(resolve(E, "empty.txt"));
    expect(r.text).toBe("");
    expect(r.warnings).toHaveLength(0);
  });

  it("whitespace-only file returns the whitespace", async () => {
    const r = await parsePlaintext(resolve(E, "whitespace.txt"));
    expect(r.text).toMatch(/^\s+$/);
  });

  it("maxFileSize=10 on a 100-byte file throws", async () => {
    await expect(
      parsePlaintext(resolve(E, "hundred-bytes.txt"), { maxFileSize: 10 }),
    ).rejects.toThrow(/exceeds max 10 bytes/);
  });
});

// ──────────────────────────────────────────────────────────────
// Cross-format via router
// ──────────────────────────────────────────────────────────────
describe("edge cases: cross-format via parse()", () => {
  it("no-extension file routes through the unsupported-extension branch (no throw)", async () => {
    const r = await parse(resolve(E, "noext"));
    expect(r.warnings.join(" ")).toMatch(/Unsupported file extension/);
    expect(r.text).toBe("");
  });

  it("filename with spaces + unicode (café test.txt) parses normally", async () => {
    const r = await parse(resolve(E, "café test.txt"));
    expect(r.method).toBe("plaintext");
    expect(r.text).toContain("unicode filename content");
    expect(r.fileName).toBe("café test.txt");
    expect(r.extension).toBe(".txt");
  });

  it("concurrent Promise.all across all formats — no race conditions / shared state", async () => {
    const [txt, docx, xlsx, pptx, pdf] = await Promise.all([
      parsePlaintext(resolve(E, "utf8-bom.txt")),
      parseDocx(resolve(E, "cyrillic.docx")),
      parseXlsx(resolve(E, "multi-sheet.xlsx")),
      parsePptx(resolve(E, "multi-slide.pptx")),
      parsePdf(resolve(E, "truncated.pdf")),
    ]);
    expect(txt.text).toContain("hello world");
    expect(docx.text).toContain("Привет");
    expect(xlsx.text).toContain("Summary");
    expect(pptx.text).toContain("Title Slide");
    expect(pdf.text).toBe("");
  });
});
